name = "bright-pastel-icons"
display-name = "Bright Pastel Icon Theme"
description = "Bright Pastel icon theme for Lapce"
version = "0.0.0"
author = "c-sleuth"
icon = "logo.png"
icon-themes = ["bright-pastel-icons.toml"]